module("datetime.py", base_path="$(BOARD_DIR)/../../modules")
module("dateHandling.py", base_path="$(BOARD_DIR)/../../modules")
module("time.py", base_path="$(BOARD_DIR)/../../modules")
module("mpy_env.py", base_path="$(BOARD_DIR)/../../modules")
module("msgpack.py", base_path="$(BOARD_DIR)/../../modules")
module("Calendar.py", base_path="$(BOARD_DIR)/../../modules")
module("Clock.py", base_path="$(BOARD_DIR)/../../modules")
package("slim", base_path="$(BOARD_DIR)/../../modules/micropython-wifi-setup/lib")
# package("micro_web_srv_2", base_path="$(BOARD_DIR)/../../modules/micropython-wifi-setup/lib")
module("logging.py","$(BOARD_DIR)/../../modules/micropython-wifi-setup/lib")
module("micro_dns_srv.py","$(BOARD_DIR)/../../modules/micropython-wifi-setup/lib")
module("shim.py","$(BOARD_DIR)/../../modules/micropython-wifi-setup/lib")
module("schedule.py","$(BOARD_DIR)/../../modules/micropython-wifi-setup/lib")
module("frozen_wifi_setup.py", base_path="$(BOARD_DIR)/../../modules")
module("frozen_micro_web_srv_2.py", base_path="$(BOARD_DIR)/../../modules")
package("mrequests", base_path="$(BOARD_DIR)/../../modules/mrequests")
module("unittest.py", base_path="$(BOARD_DIR)/../../modules")
# require("unittest")