name: Makefile CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: ['**/version.txt']
  pull_request:
    branches: [ "main" ]
    paths-ignore: ['**/version.txt']

jobs:

  esp8266:
    uses: ./.github/workflows/make_esp8266.yaml
    with:
      board: esp8266
      path: ESP8266_GENERIC

  